version: 2.1

orbs: 
  node: circleci/node@5.0.2

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:14.19.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install
      - run: mkdir ~/junit
      - run:
          command: npm run test
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ~/junit

  coverage:
    docker:
      - image: cimg/node:14.19.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Run mocha tests"
          command: npm install && npm run coverage
  deploy:
    docker:
      - image: cimg/node:14.19.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --scope=public
# Orchestrate our job run sequence
workflows:
  test_and_deploy:
    jobs:
      - test
      - coverage:
          requires: 
          - test
      - deploy:
          context:
            - NPM
          requires: 
            - test
          filters:
            branches:
              only:
                - master