version: 2.1

orbs: 
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@5.0.2

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:14.19.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Run mocha tests"
          command: |
            $COVERALLS_REPO_TOKEN=${REPO_TOKEN_BUMPVERSION}
            npm install && make test-coverage
      - coveralls/upload
  deploy:
    docker:
      - image: cimg/node:14.19.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: |
            pwd
            npm publish --scope=public
# Orchestrate our job run sequence
workflows:
  test_and_deploy:
    jobs:
      - test:
          context: 
            - COVERALLS
      - deploy:
          context:
            - NPM
          requires: 
            - test
          filters:
            branches:
              only:
                - master